In [1]:
!pip install -q awswrangler

In [2]:
import numpy as np
import pandas as pd
import boto3
from datetime import datetime, timedelta
import awswrangler as wr

In [5]:
bucket = "test-uala-arg-datalake-aiml-recommendations"

In [6]:
path_amplitude = "/data_test/amplitude"
path_cards = "/data_test/cards"

In [7]:
amplitude=wr.s3.read_parquet(f's3://test-uala-arg-datalake-aiml-recommendations/data_test/amplitude',dataset=True)

In [8]:
amplitude.shape

(935155, 12)

In [12]:
amplitude.dtypes

user_id              string
year_month           string
os_name              string
cobros                Int64
cuotificaciones       Int64
inversiones           Int64
pago_servicios        Int64
prestamos             Int64
promociones           Int64
recargas              Int64
transferencia_c2c     Int64
transferencia_cvu     Int64
dtype: object

In [41]:
cards=wr.s3.read_parquet(f's3://test-uala-arg-datalake-aiml-recommendations/data_test/cards',dataset=True)

#cards=wr.s3.read_parquet(f's3://test-uala-arg-datalake-aiml-recommendations/data/raw/cards/',dataset=True)

In [42]:
merged=pd.merge(amplitude,cards,how='inner',left_on='user_id',right_on='account_id')

In [43]:
merged.shape

(810443, 14)

In [47]:
merged[merged['account_id']=='80704ac9-a6b0-4366-908c-90b06d30a6f6']

,user_id,year_month,os_name,cobros,cuotificaciones,inversiones,pago_servicios,prestamos,promociones,recargas,transferencia_c2c,transferencia_cvu,account_id,external_id
518123,80704ac9-a6b0-4366-908c-90b06d30a6f6,2021-01,ios,0,0,2,0,0,0,0,27,2,80704ac9-a6b0-4366-908c-90b06d30a6f6,4026497

In [45]:
cards[cards['account_id']=='7884eb26-dbb2-4d5e-8397-fc248afc70e6']

                                  account_id  external_id
110813  7884eb26-dbb2-4d5e-8397-fc248afc70e6      9140245

In [46]:
amplitude[amplitude['user_id']=='7884eb26-dbb2-4d5e-8397-fc248afc70e6']

,user_id,year_month,os_name,cobros,cuotificaciones,inversiones,pago_servicios,prestamos,promociones,recargas,transferencia_c2c,transferencia_cvu
1648,7884eb26-dbb2-4d5e-8397-fc248afc70e6,2021-01,android,2,1,63,0,0,1,1,28,4

In [48]:

data=wr.s3.read_parquet(f's3://test-uala-arg-datalake-aiml-recommendations/data/stage/dt=2021-01-01/',dataset=True)

In [49]:
data.shape

(810443, 82)

In [59]:
pd.set_option('display.max_rows', 500)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 810443 entries, 0 to 33819
Data columns (total 82 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   year_month                              810443 non-null  string
 1   os_name                                 810443 non-null  string
 2   cobros                                  810443 non-null  Int64
 3   cuotificaciones                         810443 non-null  Int64
 4   inversiones                             810443 non-null  Int64
 5   pago_servicios                          810443 non-null  Int64
 6   prestamos                               810443 non-null  Int64
 7   promociones                             810443 non-null  Int64
 8   recargas                                810443 non-null  Int64
 9   transferencia_c2c                       810443 non-null  Int64
 10  transferencia_cvu                       810443 non-null  Int64
 11  account_id                              810443 non-null  string
 12  external_id                             810443 non-null  Int32
 13  vl_cashin_prestamos_sum                 810443 non-null  float64
 14  vl_cashin_adquirencia_sum               810443 non-null  float64
 15  nu_cashin_prestamos_qty                 810443 non-null  Int32
 16  nu_cashin_adquirencia_qty               810443 non-null  Int32
 17  nu_tcc_r_aprob                          810443 non-null  Int64
 18  nu_tcc_t_aprob                          810443 non-null  Int64
 19  nu_tcc_z_aprob                          810443 non-null  Int64
 20  vl_tcc_r_aprob                          810443 non-null  float64
 21  vl_tcc_t_aprob                          810443 non-null  float64
 22  vl_tcc_z_aprob                          810443 non-null  float64
 23  nu_mode_digital_qty_0_aprob             810443 non-null  Int64
 24  nu_mode_digital_qty_1_aprob             810443 non-null  Int64
 25  nu_automatic_debit_aprob                810443 non-null  Int64
 26  nu_cash_out_cvu_aprob                   810443 non-null  Int64
 27  nu_consumption_pos_aprob                810443 non-null  Int64
 28  nu_investments_deposit_aprob            810443 non-null  Int64
 29  nu_telerecargas_carga_aprob             810443 non-null  Int64
 30  nu_user_to_user_aprob                   810443 non-null  Int64
 31  nu_withdraw_atm_aprob                   810443 non-null  Int64
 32  vl_automatic_debit_aprob                810443 non-null  float64
 33  vl_cash_out_cvu_aprob                   810443 non-null  float64
 34  vl_consumption_pos_aprob                810443 non-null  float64
 35  vl_investments_deposit_aprob            810443 non-null  float64
 36  vl_telerecargas_carga_aprob             810443 non-null  float64
 37  vl_user_to_user_aprob                   810443 non-null  float64
 38  vl_withdraw_atm_aprob                   810443 non-null  float64
 39  nu_compras_aprob                        810443 non-null  Int64
 40  nu_entretenimiento_aprob                810443 non-null  Int64
 41  nu_servicios_débitos_automaticos_aprob  810443 non-null  Int64
 42  nu_supermercados_alimentos_aprob        810443 non-null  Int64
 43  nu_transferencias_retiros_aprob         810443 non-null  Int64
 44  vl_compras_aprob                        810443 non-null  float64
 45  vl_entretenimiento_aprob                810443 non-null  float64
 46  vl_servicios_débitos_automaticos_aprob  810443 non-null  float64
 47  vl_supermercados_alimentos_aprob        810443 non-null  float64
 48  vl_transferencias_retiros_aprob         810443 non-null  float64
 49  nu_tcc_r_rech                           810443 non-null  Int64
 50  nu_tcc_t_rech                           810443 non-null  Int64
 51  nu_tcc_z_rech                           810443 non-null  Int64
 52  vl_tcc_r_rech                           810443 non-null  float64
 53  vl_tcc_t_rech                           810443 non-null  float64
 54  vl_tcc_z_rech                           810443 non-null  float64
 55  nu_mode_digital_qty_0_rech              810443 non-null  Int64
 56  nu_mode_digital_qty_1_rech              810443 non-null  Int64
 57  nu_automatic_debit_rech                 810443 non-null  Int64
 58  nu_cash_out_cvu_rech                    810443 non-null  Int64
 59  nu_consumption_pos_rech                 810443 non-null  Int64
 60  nu_investments_deposit_rech             810443 non-null  Int64
 61  nu_telerecargas_carga_rech              810443 non-null  Int64
 62  nu_user_to_user_rech                    810443 non-null  Int64
 63  nu_withdraw_atm_rech                    810443 non-null  Int64
 64  vl_automatic_debit_rech                 810443 non-null  float64
 65  vl_cash_out_cvu_rech                    810443 non-null  float64
 66  vl_consumption_pos_rech                 810443 non-null  float64
 67  vl_investments_deposit_rech             810443 non-null  float64
 68  vl_telerecargas_carga_rech              810443 non-null  float64
 69  vl_user_to_user_rech                    810443 non-null  float64
 70  vl_withdraw_atm_rech                    810443 non-null  float64
 71  nu_compras_rech                         810443 non-null  Int64
 72  nu_entretenimiento_rech                 810443 non-null  Int64
 73  nu_servicios_débitos_automaticos_rech   810443 non-null  Int64
 74  nu_supermercados_alimentos_rech         810443 non-null  Int64
 75  nu_transferencias_retiros_rech          810443 non-null  Int64
 76  vl_compras_rech                         810443 non-null  float64
 77  vl_entretenimiento_rech                 810443 non-null  float64
 78  vl_servicios_débitos_automaticos_rech   810443 non-null  float64
 79  vl_supermercados_alimentos_rech         810443 non-null  float64
 80  vl_transferencias_retiros_rech          810443 non-null  float64
 81  dt                                      810443 non-null  category
dtypes: Int32(3), Int64(43), category(1), float64(32), string(3)
memory usage: 534.1 MB

In [61]:
pd.set_option('display.max_columns', 500)
data.head(5)

,year_month,os_name,cobros,cuotificaciones,inversiones,pago_servicios,prestamos,promociones,recargas,transferencia_c2c,transferencia_cvu,account_id,external_id,vl_cashin_prestamos_sum,vl_cashin_adquirencia_sum,nu_cashin_prestamos_qty,nu_cashin_adquirencia_qty,nu_tcc_r_aprob,nu_tcc_t_aprob,nu_tcc_z_aprob,vl_tcc_r_aprob,vl_tcc_t_aprob,vl_tcc_z_aprob,nu_mode_digital_qty_0_aprob,nu_mode_digital_qty_1_aprob,nu_automatic_debit_aprob,nu_cash_out_cvu_aprob,nu_consumption_pos_aprob,nu_investments_deposit_aprob,nu_telerecargas_carga_aprob,nu_user_to_user_aprob,nu_withdraw_atm_aprob,vl_automatic_debit_aprob,vl_cash_out_cvu_aprob,vl_consumption_pos_aprob,vl_investments_deposit_aprob,vl_telerecargas_carga_aprob,vl_user_to_user_aprob,vl_withdraw_atm_aprob,nu_compras_aprob,nu_entretenimiento_aprob,nu_servicios_débitos_automaticos_aprob,nu_supermercados_alimentos_aprob,nu_transferencias_retiros_aprob,vl_compras_aprob,vl_entretenimiento_aprob,vl_servicios_débitos_automaticos_aprob,vl_supermercados_alimentos_aprob,vl_transferencias_retiros_aprob,nu_tcc_r_rech,nu_tcc_t_rech,nu_tcc_z_rech,vl_tcc_r_rech,vl_tcc_t_rech,vl_tcc_z_rech,nu_mode_digital_qty_0_rech,nu_mode_digital_qty_1_rech,nu_automatic_debit_rech,nu_cash_out_cvu_rech,nu_consumption_pos_rech,nu_investments_deposit_rech,nu_telerecargas_carga_rech,nu_user_to_user_rech,nu_withdraw_atm_rech,vl_automatic_debit_rech,vl_cash_out_cvu_rech,vl_consumption_pos_rech,vl_investments_deposit_rech,vl_telerecargas_carga_rech,vl_user_to_user_rech,vl_withdraw_atm_rech,nu_compras_rech,nu_entretenimiento_rech,nu_servicios_débitos_automaticos_rech,nu_supermercados_alimentos_rech,nu_transferencias_retiros_rech,vl_compras_rech,vl_entretenimiento_rech,vl_servicios_débitos_automaticos_rech,vl_supermercados_alimentos_rech,vl_transferencias_retiros_rech,dt
0,2021-01,android,0,0,2,0,0,2,0,3,0,2fac1fe1-cf8c-4e5f-9291-97570ed33a9f,100040,0.0,0.0,0,0,0,0,0,0.0,0.00,0.0,0,0,0,0,0,0,0,0,0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.00,0.0,0.0,0.0,0,0,0,0.0,0.00,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.00,0.0,0.0,0.0,2021-01-01
1,2021-01,android,0,0,0,0,0,1,0,6,1,a4fac485-8514-44db-a8fa-1ad0dcfab03d,100146,0.0,0.0,0,0,0,1,0,0.0,3.99,0.0,1,0,1,0,0,0,0,0,0,3.99,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0.0,3.99,0.0,0.0,0.0,0,4,0,0.0,4.04,0.0,0,4,0,0,4,0,0,0,0,0.0,0.0,4.04,0.0,0.0,0.0,0.0,0,4,0,0,0,0.0,4.04,0.0,0.0,0.0,2021-01-01
2,2021-01,android,0,0,1,0,0,0,0,0,0,c9b24f21-c34a-47c5-8412-32e0b351e9d2,100485,0.0,0.0,0,0,0,0,0,0.0,0.00,0.0,0,0,0,0,0,0,0,0,0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.00,0.0,0.0,0.0,0,0,0,0.0,0.00,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.00,0.0,0.0,0.0,2021-01-01
3,2021-01,android,0,0,2,0,0,0,0,0,0,fa7e000e-5cc2-4ce4-9f54-7ffd9ef857d5,100942,0.0,0.0,0,0,0,0,0,0.0,0.00,0.0,0,0,0,0,0,0,0,0,0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.00,0.0,0.0,0.0,0,0,0,0.0,0.00,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.00,0.0,0.0,0.0,2021-01-01
4,2021-01,android,0,0,0,1,0,0,0,1,0,d307c3a2-a8db-42ea-b21c-95027177dcd9,101162,0.0,0.0,0,0,0,0,0,0.0,0.00,0.0,0,0,0,0,0,0,0,0,0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.00,0.0,0.0,0.0,0,0,0,0.0,0.00,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.00,0.0,0.0,0.0,2021-01-01

In [31]:
data=wr.s3.read_parquet(f's3://test-uala-arg-datalake-aiml-recommendations/data/stage/test',dataset=True)

InvalidArgumentValue: Object s3://test-uala-arg-datalake-aiml-recommendations/data/stage/dt=2020-05-01/part-00001-ec2cb95b-1572-48c2-9181-bf81b5caa48c-c000.snappy.parquet is not under the root path (s3://test-uala-arg-datalake-aiml-recommendations/data/stage/dt=2020-05-01/part-00001-ec2cb95b-1572-48c2-9181-bf81b5caa48c-c000.snappy.parquet/).

In [4]:
def list_objects_function(buckets_, keys_):
    
    s3 = boto3.resource('s3')
    bucket = s3.Bucket(buckets_)
    files_in_bucket = list(bucket.objects.all())
    files_objets = [f"s3://{buckets_}/" + i.key for i in files_in_bucket if
                        (i.key.find(keys_) >= 0) and (i.key.find('.parquet') >= 0)]
    df_bucket_files = pd.DataFrame({
            'key': [i[:(i.find('dt=') + 14)] for i in files_objets],
            'path': files_objets,
            'date': pd.to_datetime([i[(i.find('dt=') + 3):(i.find('dt=') + 13)] for i in files_objets])
        })
    files=df_bucket_files
    return files

In [19]:
list_files=list_objects_function('test-uala-arg-datalake-aiml-recommendations','data/stage/splited_data').date.astype(str).unique()

In [20]:
list_files

array(['2020-05-01', '2020-06-01', '2020-07-01', '2020-08-01',
       '2020-09-01', '2020-10-01', '2020-11-01', '2020-12-01',
       '2021-01-01', '2021-02-01', '2021-03-01'], dtype=object)

In [ ]:
list_files

In [48]:
list_files=list_files[1:3]

In [49]:
data=wr.s3.read_parquet(*list_files[1],dataset=True)

TypeError: read_parquet() got multiple values for argument 'dataset'

In [6]:
data_total=pd.DataFrame()
for row in list_files:
    data=wr.s3.read_parquet(f's3://test-uala-arg-datalake-aiml-recommendations/data/stage/dt={row}',dataset=True)
    data_total=pd.concat([data,data_total], ignore_index=True)
    print(data['dt'].unique())
    print(len(data))

['2020-05-01']
Categories (1, object): ['2020-05-01']
418785
['2020-06-01']
Categories (1, object): ['2020-06-01']
566616
['2020-07-01']
Categories (1, object): ['2020-07-01']
688502
['2020-08-01']
Categories (1, object): ['2020-08-01']
698693
['2020-09-01']
Categories (1, object): ['2020-09-01']
707927
['2020-10-01']
Categories (1, object): ['2020-10-01']
713354
['2020-11-01']
Categories (1, object): ['2020-11-01']
736001
['2020-12-01']
Categories (1, object): ['2020-12-01']
980034
['2021-01-01']
Categories (1, object): ['2021-01-01']
810443
['2021-02-01']
Categories (1, object): ['2021-02-01']
798682
['2021-03-01']
Categories (1, object): ['2021-03-01']
875429

In [7]:
data_total.shape

(7994466, 82)

In [9]:
wr.s3.to_parquet(
    df=data_total,
    path='s3://test-uala-arg-datalake-aiml-recommendations/data/stage/all_data',
    dataset=True)

{'paths': ['s3://test-uala-arg-datalake-aiml-recommendations/data/stage/all_data/eec2687a7b744486a8cecb9a0d4c97fc.snappy.parquet'],
 'partitions_values': {}}

In [17]:
data_total[data_total.dt=='2020-11-01'].inversiones.sum()

2555447

In [3]:

data=wr.s3.read_parquet(f's3://test-uala-arg-datalake-aiml-recommendations/data/stage/all_data/',dataset=True)

In [4]:
data.shape

(7994466, 82)